version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    ports:
      - 5672:5672
      - 8080:15672
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  normalizer:
    build:
      context: .
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
    depends_on:
      - rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_APP_ID=sizematch-item-normalizer
      - CONSUMER_QUEUE_NAME=sizematch-item-normalizer
      - PREFETCH_COUNT=2
      - PUBLISHER_EXCHANGE_NAME=sizematch-items
      - PUBLISHER_ROUTING_KEY=items.save
      - PUBLISHER_QUEUE_NAME=sizematch-item-saver
